### ISSUE TITLE
ansible 简单实用 批量管理多个设备

### ISSUE THREAD

**Issue by xx-zhang** [xx-zhang/docker-t50#2]
### 建立playbook文件
```
cat > /etc/ansible/push-key.yaml  << EOF
# Using alternate directory locations:
  - hosts: kvm_test
    user: root
    tasks:
     - name: ssh-copy
       authorized_key: user=root key="{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
       tags:
         - sshkey
EOF
```
### 修改cfg
```
cat /etc/ansible/ansible.cfg | grep host_key_checking 
# 修改grep host_key_checking  为 False
tsh = `sed -i 's/#host_key_checking/host_key_checking' /etc/ansible/ansible.cfg `
```
### 加入 /etc/ansbile/hosts
```
[kvm_hosts]
192.168.2.55  ansible_user=root ansible_ssh_pass="1111111"
192.168.2.17  ansible_user=root ansible_ssh_pass="111111"
192.168.2.223  ansible_user=root ansible_ssh_pass="1111111"
192.168.2.99  ansible_user=root ansible_ssh_pass="111111"
192.168.2.41  ansible_user=root ansible_ssh_pass="111111"
192.168.2.73  ansible_user=root ansible_ssh_pass="111111"
192.168.2.189  ansible_user=root ansible_ssh_pass="111111"
192.168.2.175  ansible_user=root ansible_ssh_pass="111111"
192.168.2.227  ansible_user=root ansible_ssh_pass="1111.."
# 192.168.2.227  ansible_user=root ansible_ssh_pass="11111"
```
### 加载密钥
```bash
ansible-playbook /etc/ansible/push-key.yaml
```
